#!/bin/bash
#=============================================================================
# InfraStack - Network Configuration Generator
# Part of InfraStack sysadmin infrastructure toolkit
#
# Description: Generate port forwarding and NAT rules (does NOT apply them)
# Usage: infrastack network generate-forwarding --ctid <id> --type <type>
# Author: TecnoSoul
#=============================================================================

set -euo pipefail

# Source common library
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

#=============================================================================
# CONFIGURATION
#=============================================================================

# Detect Proxmox host configuration
detect_host_config() {
    local hostname=$(hostname -f)
    
    # Try to get public IP from default route
    local public_ip=$(ip route get 8.8.8.8 | grep -oP 'src \K\S+')
    
    log_info "Detected configuration:"
    echo "  Hostname: $hostname"
    echo "  Public IP: $public_ip"
}

#=============================================================================
# PORT FORWARDING GENERATORS
#=============================================================================

# Function: generate_virtualmin_forwarding
# Purpose: Generate port forwarding rules for Virtualmin hosting
# Parameters:
#   $1 - ctid
#   $2 - internal_ip
#   $3 - public_ip
#   $4 - ssh_port (optional, default: 2200+ctid)
generate_virtualmin_forwarding() {
    local ctid=$1
    local internal_ip=$2
    local public_ip=$3
    local ssh_port=${4:-$((2200 + ctid))}
    
    cat << EOF
#!/bin/bash
#=============================================================================
# Port Forwarding Configuration for Virtualmin Hosting
# Container: CT${ctid}
# Internal IP: ${internal_ip}
# Public IP: ${public_ip}
#
# Generated by: InfraStack Network Configuration Generator
# Date: $(date '+%Y-%m-%d %H:%M:%S')
#
# IMPORTANT: Review this script before executing!
#            Test in a safe environment first.
#=============================================================================

# Backup existing rules
echo "Creating backup of current iptables rules..."
iptables-save > /root/iptables-backup-\$(date +%Y%m%d-%H%M%S).txt

# SSH Access (external port ${ssh_port} -> CT${ctid}:22)
iptables -t nat -A PREROUTING -d ${public_ip} -p tcp --dport ${ssh_port} \\
    -j DNAT --to-destination ${internal_ip}:22

# HTTP/HTTPS (80, 443)
iptables -t nat -A PREROUTING -d ${public_ip} -p tcp --dport 80 \\
    -j DNAT --to-destination ${internal_ip}:80
iptables -t nat -A PREROUTING -d ${public_ip} -p tcp --dport 443 \\
    -j DNAT --to-destination ${internal_ip}:443

# DNS (53 TCP and UDP)
iptables -t nat -A PREROUTING -d ${public_ip} -p udp --dport 53 \\
    -j DNAT --to-destination ${internal_ip}:53
iptables -t nat -A PREROUTING -d ${public_ip} -p tcp --dport 53 \\
    -j DNAT --to-destination ${internal_ip}:53

# Mail Ports
# SMTP (25)
iptables -t nat -A PREROUTING -d ${public_ip} -p tcp --dport 25 \\
    -j DNAT --to-destination ${internal_ip}:25

# Submission (587)
iptables -t nat -A PREROUTING -d ${public_ip} -p tcp --dport 587 \\
    -j DNAT --to-destination ${internal_ip}:587

# IMAPS (993)
iptables -t nat -A PREROUTING -d ${public_ip} -p tcp --dport 993 \\
    -j DNAT --to-destination ${internal_ip}:993

# POP3S (995)
iptables -t nat -A PREROUTING -d ${public_ip} -p tcp --dport 995 \\
    -j DNAT --to-destination ${internal_ip}:995

# IMAP (143)
iptables -t nat -A PREROUTING -d ${public_ip} -p tcp --dport 143 \\
    -j DNAT --to-destination ${internal_ip}:143

# POP3 (110)
iptables -t nat -A PREROUTING -d ${public_ip} -p tcp --dport 110 \\
    -j DNAT --to-destination ${internal_ip}:110

# Webmin (10000)
iptables -t nat -A PREROUTING -d ${public_ip} -p tcp --dport 10000 \\
    -j DNAT --to-destination ${internal_ip}:10000

# Webmin RPC Cluster Communication (10001-10010)
for port in {10001..10010}; do
    iptables -t nat -A PREROUTING -d ${public_ip} -p tcp --dport \$port \\
        -j DNAT --to-destination ${internal_ip}:\$port
done

echo "✓ Port forwarding rules added for CT${ctid}"
echo ""
echo "To make these rules permanent:"
echo "  netfilter-persistent save"
echo ""
echo "To verify rules:"
echo "  iptables -t nat -L PREROUTING -n -v | grep ${internal_ip}"

EOF
}

# Function: generate_basic_nat
# Purpose: Generate basic NAT configuration for internal network
generate_basic_nat() {
    local internal_network=${1:-192.168.2.0/24}
    local public_interface=${2:-vmbr0}
    
    cat << EOF
#!/bin/bash
#=============================================================================
# Basic NAT Configuration for Internal Network
# Network: ${internal_network}
# Public Interface: ${public_interface}
#
# Generated by: InfraStack Network Configuration Generator
# Date: $(date '+%Y-%m-%d %H:%M:%S')
#=============================================================================

# Enable IP forwarding
echo "Enabling IP forwarding..."
sysctl -w net.ipv4.ip_forward=1

# Make permanent
if ! grep -q "net.ipv4.ip_forward=1" /etc/sysctl.conf; then
    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
fi

# NAT rule for internal network
iptables -t nat -A POSTROUTING -s ${internal_network} -o ${public_interface} -j MASQUERADE

echo "✓ NAT configured for ${internal_network}"
echo ""
echo "To make permanent:"
echo "  netfilter-persistent save"
echo ""
echo "To verify:"
echo "  iptables -t nat -L POSTROUTING -n -v | grep MASQUERADE"

EOF
}

# Function: generate_remove_forwarding
# Purpose: Generate script to remove port forwarding rules
# Parameters:
#   $1 - ctid
#   $2 - internal_ip
#   $3 - public_ip
generate_remove_forwarding() {
    local ctid=$1
    local internal_ip=$2
    local public_ip=$3
    
    cat << EOF
#!/bin/bash
#=============================================================================
# Remove Port Forwarding for CT${ctid}
# Internal IP: ${internal_ip}
# Public IP: ${public_ip}
#
# Generated by: InfraStack Network Configuration Generator
# Date: $(date '+%Y-%m-%d %H:%M:%S')
#=============================================================================

echo "Removing port forwarding rules for CT${ctid} (${internal_ip})..."

# Delete all PREROUTING rules for this container's internal IP
iptables-save | grep "${internal_ip}" | grep "\-A PREROUTING" | sed 's/-A //' | while read rule; do
    iptables -t nat -D \$rule 2>/dev/null && echo "  Removed: \$rule"
done

echo ""
echo "✓ Port forwarding rules removed for CT${ctid}"
echo ""
echo "To make permanent:"
echo "  netfilter-persistent save"

EOF
}

#=============================================================================
# MAIN FUNCTIONS
#=============================================================================

# Function: generate_config
# Purpose: Main configuration generator
generate_config() {
    local ctid=""
    local type=""
    local public_ip=""
    local output_file=""
    
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --ctid) ctid="$2"; shift 2 ;;
            --type) type="$2"; shift 2 ;;
            --public-ip) public_ip="$2"; shift 2 ;;
            --output) output_file="$2"; shift 2 ;;
            *) log_error "Unknown option: $1"; exit 1 ;;
        esac
    done
    
    # Validate required parameters
    if [[ -z "$ctid" ]] || [[ -z "$type" ]]; then
        log_error "Required: --ctid and --type"
        show_usage
        exit 1
    fi
    
    # Auto-detect public IP if not provided
    if [[ -z "$public_ip" ]]; then
        public_ip=$(ip route get 8.8.8.8 | grep -oP 'src \K\S+')
        log_info "Auto-detected public IP: $public_ip"
    fi
    
    # Get container's internal IP
    local internal_ip
    if ! pct status "$ctid" &>/dev/null; then
        log_error "Container $ctid does not exist"
        exit 1
    fi
    
    internal_ip=$(pct config "$ctid" | grep -oP 'ip=\K[^/]+' | head -1)
    
    if [[ -z "$internal_ip" ]]; then
        log_error "Could not determine internal IP for container $ctid"
        exit 1
    fi
    
    log_info "Container CT${ctid} internal IP: $internal_ip"
    
    # Set default output file
    if [[ -z "$output_file" ]]; then
        output_file="/root/port-forward-ct${ctid}.sh"
    fi
    
    # Generate appropriate configuration
    case "$type" in
        virtualmin|hosting)
            log_info "Generating Virtualmin port forwarding configuration..."
            generate_virtualmin_forwarding "$ctid" "$internal_ip" "$public_ip" > "$output_file"
            ;;
        remove)
            log_info "Generating removal script..."
            generate_remove_forwarding "$ctid" "$internal_ip" "$public_ip" > "$output_file"
            ;;
        *)
            log_error "Unknown type: $type"
            log_info "Supported types: virtualmin, hosting, remove"
            exit 1
            ;;
    esac
    
    # Make executable
    chmod +x "$output_file"
    
    # Success message
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    log_success "Configuration script generated!"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Script location: $output_file"
    echo ""
    echo "Next steps:"
    echo "  1. Review the script: cat $output_file"
    echo "  2. Execute (if correct): $output_file"
    echo "  3. Save permanently: netfilter-persistent save"
    echo "  4. Test connectivity from external network"
    echo ""
    echo "⚠️  WARNING: Review the script before executing!"
    echo "   Network changes can break connectivity."
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
}

# Function: generate_nat_config
# Purpose: Generate basic NAT configuration
generate_nat_config() {
    local output_file="/root/setup-nat.sh"
    
    log_info "Generating NAT configuration..."
    
    generate_basic_nat > "$output_file"
    chmod +x "$output_file"
    
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    log_success "NAT configuration script generated!"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Script location: $output_file"
    echo ""
    echo "This script will:"
    echo "  • Enable IP forwarding"
    echo "  • Configure NAT for internal network (192.168.2.0/24)"
    echo "  • Allow containers to access internet"
    echo ""
    echo "Review and execute: $output_file"
    echo ""
}

# Function: show_current_rules
# Purpose: Display current NAT and forwarding rules
show_current_rules() {
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "Current NAT Rules"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    iptables -t nat -L POSTROUTING -n -v
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "Current Port Forwarding Rules"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    iptables -t nat -L PREROUTING -n -v
    echo ""
}

#=============================================================================
# USAGE AND HELP
#=============================================================================

show_usage() {
    cat << EOF
InfraStack - Network Configuration Generator

This tool GENERATES configuration scripts but does NOT apply them.
Always review generated scripts before executing!

Usage: $0 <command> [options]

Commands:
    generate-forwarding     Generate port forwarding rules for a container
    generate-nat            Generate basic NAT configuration
    show-rules              Display current iptables rules

Options for generate-forwarding:
    --ctid ID               Container ID (required)
    --type TYPE             Type: virtualmin, hosting, remove (required)
    --public-ip IP          Public IP (auto-detected if not provided)
    --output FILE           Output file path (default: /root/port-forward-ctID.sh)

Examples:
    # Generate port forwarding for Virtualmin hosting server
    $0 generate-forwarding --ctid 103 --type virtualmin

    # Generate removal script
    $0 generate-forwarding --ctid 103 --type remove

    # Generate NAT configuration
    $0 generate-nat

    # Show current rules
    $0 show-rules

Safety Features:
    ✓ Scripts are generated, not executed
    ✓ Backups are included in generated scripts
    ✓ Clear warnings and instructions provided
    ✓ Review before execution required

EOF
}

#=============================================================================
# MAIN
#=============================================================================

main() {
    if [[ $# -eq 0 ]]; then
        show_usage
        exit 0
    fi
    
    local command=$1
    shift
    
    case "$command" in
        generate-forwarding)
            check_root
            generate_config "$@"
            ;;
        generate-nat)
            check_root
            generate_nat_config
            ;;
        show-rules)
            check_root
            show_current_rules
            ;;
        help|--help|-h)
            show_usage
            ;;
        *)
            log_error "Unknown command: $command"
            show_usage
            exit 1
            ;;
    esac
}

main "$@"